INSERT INTO audit_event_type (resource_type_id, id) VALUES
    ('USER', 'USER_REGISTERED'),
    ('USER', 'USER_LOGGED_IN'),
    ('USER', 'USER_PASSWORD_CHANGED'),
    ('USER', 'USER_PERMISSIONS_UPDATED'),
    ('USER', 'USER_UPDATED'),

    ('BOOK', 'BOOK_CREATED'),
    ('BOOK', 'BOOK_UPDATED'),
    ('BOOK', 'BOOK_BORROWED'),
    ('BOOK', 'BOOK_RETURNED'),

    ('BOOK_CATEGORY', 'BOOK_CATEGORY_CREATED'),
    ('BOOK_CATEGORY', 'BOOK_CATEGORY_UPDATED'),
    ('BOOK_CATEGORY', 'BOOK_CATEGORIES_MERGED'),

    ('AUTHOR', 'AUTHOR_CREATED'),
    ('AUTHOR', 'AUTHOR_UPDATED'),

    ('PUBLISHER', 'PUBLISHER_CREATED'),
    ('PUBLISHER', 'PUBLISHER_UPDATED'),
    ('PUBLISHER', 'PUBLISHERS_MERGED');